-- ============================================================
-- QuantBid Arena — Schema Migration v2
-- Run this entire file in your Supabase SQL Editor.
-- Safe to run multiple times (uses IF NOT EXISTS).
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. Extend the existing `questions` table
-- ────────────────────────────────────────────────────────────

ALTER TABLE public.questions
  ADD COLUMN IF NOT EXISTS status               TEXT        NOT NULL DEFAULT 'AVAILABLE',
  ADD COLUMN IF NOT EXISTS current_bid_amount   INTEGER,
  ADD COLUMN IF NOT EXISTS current_bid_team_id  BIGINT      REFERENCES public.teams(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS original_base_price  INTEGER,
  ADD COLUMN IF NOT EXISTS original_reward_points INTEGER,
  ADD COLUMN IF NOT EXISTS original_time_limit  INTEGER,
  ADD COLUMN IF NOT EXISTS re_auction_count     INTEGER     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS excluded_team_ids    JSONB       NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS active_time_seconds  INTEGER,
  ADD COLUMN IF NOT EXISTS solve_started_at     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS double_reward_team_id BIGINT     REFERENCES public.teams(id) ON DELETE SET NULL;

-- Reset any stuck statuses back to AVAILABLE so the game can start
-- (Only runs once — questions in terminal states are left alone)
UPDATE public.questions
  SET status = 'AVAILABLE',
      current_bid_amount = NULL,
      current_bid_team_id = NULL,
      assigned_team_id = NULL,
      re_auction_count = 0,
      excluded_team_ids = '[]'::jsonb,
      active_time_seconds = NULL,
      solve_started_at = NULL,
      double_reward_team_id = NULL,
      is_used = false
  WHERE status NOT IN ('SOLVED', 'CLOSED');

-- ────────────────────────────────────────────────────────────
-- 2. `teams` table — no structural change needed.
--    `score` = Reward Points (RP), `balance` = Quant Money (QM).
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- 3. Create `bids` table
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.bids (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  team_id     BIGINT NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  amount      INTEGER NOT NULL,
  placed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bids_question_id_idx ON public.bids (question_id);
CREATE INDEX IF NOT EXISTS bids_team_id_idx     ON public.bids (team_id);

-- ────────────────────────────────────────────────────────────
-- 4. Create `power_cards` table (one row per team)
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.power_cards (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id             BIGINT NOT NULL UNIQUE REFERENCES public.teams(id) ON DELETE CASCADE,
  extra_time_used     BOOLEAN NOT NULL DEFAULT false,
  double_reward_used  BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed one power_card row per existing team (safe if already exists)
INSERT INTO public.power_cards (team_id)
SELECT id FROM public.teams
ON CONFLICT (team_id) DO NOTHING;

-- ────────────────────────────────────────────────────────────
-- 5. Create `transactions` ledger
-- ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.transactions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id     BIGINT NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  qm_delta    INTEGER NOT NULL DEFAULT 0,
  rp_delta    INTEGER NOT NULL DEFAULT 0,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS transactions_team_id_idx ON public.transactions (team_id);

-- ────────────────────────────────────────────────────────────
-- Done. All migrations applied.
-- ────────────────────────────────────────────────────────────
