create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  score integer not null default 0,
  balance integer not null default 2500,
  color text,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  answer_text text,
  options jsonb default '[]'::jsonb,
  reward_points integer not null default 10,
  base_amount integer not null default 500,
  time_limit_seconds integer not null default 30,
  is_used boolean not null default false,
  category text,
  difficulty text,
  assigned_team_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists questions_is_used_idx on public.questions (is_used);
create index if not exists questions_assigned_team_id_idx on public.questions (assigned_team_id);

-- Optional seed data
insert into public.teams (name, score, balance, color)
values
  ('Euler Titans', 0, 10000, '#2fd4ff'),
  ('Gauss Guardians', 0, 10000, '#80ffcf'),
  ('Noether Knights', 0, 10000, '#ff9ec7')
on conflict (name) do nothing;

insert into public.questions (
  question_text,
  answer_text,
  options,
  reward_points,
  base_amount,
  time_limit_seconds,
  category,
  difficulty
)
values
  (
    'If x^2 - 5x + 6 = 0, what is x + 1 for the larger root?',
    '4',
    '["2", "3", "4", "5"]'::jsonb,
    10,
    1000,
    30,
    'Algebra',
    'Easy'
  ),
  (
    'Evaluate the determinant of [[1,2],[3,4]].',
    '-2',
    '["2", "-2", "4", "-4"]'::jsonb,
    20,
    1500,
    40,
    'Linear Algebra',
    'Medium'
  )
on conflict do nothing;
